// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/22/2024, 2:56:26 PM
const configMerger = require("/home/andix/andixblog/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/home/andix/andixblog/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/andix/andixblog/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/andix/andixblog/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/andix/andixblog/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/andix/andixblog/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/andix/andixblog/plugins/**/*.{js,ts,mjs}","/home/andix/andixblog/composables/**/*.{js,ts,mjs}","/home/andix/andixblog/utils/**/*.{js,ts,mjs}","/home/andix/andixblog/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/andix/andixblog/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/andix/andixblog/app.config.{js,ts,mjs}"] }));

module.exports = (() => {const cfg=config;cfg["content"]["13"] = "/home/andix/andixblog/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})()
